// import prisma client from node_modules (generated by "prisma generate")
const { PrismaClient } = require('@prisma/client')

// initially with empty options object to use defaults from prisma.config.ts
export const prismaClient = new PrismaClient()